version: "3"
services:
  web:
    container_name: call-center
    build: .
    # command: python3 app/app.py
    # volumes:
    #   - ./app:/app
    ports:
      - 5000:5000
    env_file:
      - .env
    tty: true
